# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_device_id": "00_client.ipynb",
         "DecadesClient": "00_client.ipynb",
         "play": "00_client.ipynb",
         "ADCDevice": "01_controls.ipynb",
         "ADS7830": "01_controls.ipynb",
         "DecadesDial": "01_controls.ipynb",
         "PowerButton": "01_controls.ipynb",
         "Controller": "01_controls.ipynb",
         "run_radio": "02_player.ipynb"}

modules = ["client.py",
           "controls.py",
           "player.py"]

doc_url = "https://bwolfson97.github.io/time_travel_radio/"

git_url = "https://github.com/bwolfson97/time_travel_radio/tree/master/"

def custom_doc_links(name): return None
