# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_device_id": "00_core.ipynb",
         "MusicPlayer": "00_core.ipynb",
         "play": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://bwolfson97.github.io/time_travel_radio/"

git_url = "https://github.com/bwolfson97/time_travel_radio/tree/master/"

def custom_doc_links(name): return None
