# AUTOGENERATED! DO NOT EDIT! File to edit: 02_player.ipynb (unless otherwise specified).

__all__ = ['run_radio']

# Cell
from .client import DecadesClient
from .controls import Controller
from fastcore.script import *

# Cell
@call_parse
def run_radio(
    pwr: Param("GPIO pin of power button", int),
    name: Param("Name of device", str)="Brandon's Raspberry Pi"
) -> None:
    client = DecadesClient(device_name)
    controller = Controller(client.playlists, power_button_gpio_pin)

    while True:
        actions = controller.read_controls()
        if actions["change_decade"] is not None:
            client.play_music(actions["change_decade"])